spring.profiles.active=dev

spring.application.name=schoolapp
#server.servlet.context-path=/schoolapp

spring.jpa.hibernate.ddl-auto=validate

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration


#το session κλεινει αυτοματα οταν επιστεψει το service
#αν ηταν true θα κρατουσε το session ανοιχτο και θα μπορουσε να κανει lazy
#loading n+1 queries osiv =  true
#Best practice ειναι false
#Join fetch ή EntityGraph
spring.jpa.open-in-view=false